# Generated by Django 4.2.5 on 2023-09-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_rename_tipo_habitacion_tipo_habitacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='fecha_disponible_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='fecha_disponible_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='disponible',
            field=models.BooleanField(default=False),
        ),
    ]
